<!DOCTYPE html>
<html>
<!--
/************************************************/
/*	  	.:: Par Buffet Christophe ::.	  		*/
/*			.:: 0032(0)/474/171.255 ::.  		*/
/*	.:: Copyright  www.tinyurl.com/copy4u ::.	*/
/*	     .:: http://crystal-web.org ::.         */
/************************************************/
-->
<head>
	<title>Crystal-Web</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<meta name="language" content="fr">

	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<link rel="stylesheet" href="http://cdn.crystal-web.org/files/css/bootstrap/1.4.0/bootstrap.min.css">
	<?php echo $mvc->Page->getHeader(); ?>
<script type="text/javascript">
<!--
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29895156-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

--></script>
<link rel=stylesheet type="text/css" href="http://cdn.crystal-web.org/files/css/common.css">
	
<style type="text/css">
body{
background-color: whiteSmoke;
}
</style>

</head>

  <body>

      <div class="content" style="padding: 10px;">
        <div style="padding:10px;">
				<?php
				echo $mvc->Session->flash();		
				echo $mvc->contenu;
				?>
        </div>
      </div>
	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/bootstrap-tabs.js">$('.tabs').tabs();</script>

</body>
</html>
