<!DOCTYPE html>
<html>
<!--
/************************************************/
/*	  	.:: Par Buffet Christophe ::.	  		*/
/*			.:: 0032(0)/474/171.255 ::.  		*/
/*	.:: Copyright  www.tinyurl.com/copy4u ::.	*/
/*	     .:: http://crystal-web.org ::.         */
/************************************************/
-->
<head>
	<title><?php echo $mvc->Page->getPageTitle() . ' | ' . $mvc->Page->getSiteTitle(); ?></title>
 
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<meta http-equiv="content-language" content="" />
	<meta name="dc.title" content="<?php echo $mvc->Page->getPageTitle() . ' | ' . $mvc->Page->getSiteTitle(); ?>" />
	<meta name="language" content="fr">
	<link rel="icon" type="image/x-icon" href="<?php echo __CW_PATH; ?>/favicon.ico">
	<link rel="icon" type="image/png" href="<?php echo __CW_PATH; ?>/favicon.png">
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
	
<style type="text/css">
*{margin:0;padding:0;}
a{color:#FFF;text-decoration: none;outline: none;}
a:hover{text-decoration: underline;}
img{border:none;}
body {overflow:hidden;/*Needed to eliminate scrollbars*/ background:#E5690B;}
#content{margin:0px auto;height:130px;width:100%;bottom:45%;z-index: 3;background:#262626 no-repeat 90%;border-top:1px solid #000;border-bottom:1px solid #4F4F4F;position:absolute;}
#contentframe{overflow: hidden;border-top:solid 1px #4F4F4F;border-bottom:1px solid #000;height: 100%;text-align:left;z-index: 3;}
#slidecaption{overflow: hidden;color:#FFF;font:26px "Helvetica Neue", Arial, sans-serif;font-weight:bold;margin:33px 0;}
</style>


<!-- FIN DU SCRIPT -->
</head>

<body>

<div id="content">
	<div id="contentframe">
		<div id="slidecaption">

				<p style="text-align: center; "><?php				
				echo $mvc->Session->flash();
				?></p>

		</div>
						
					
			
	</div> <?php echo $mvc->contenu; ?>
</div>



<div style="position: absolute;bottom:0;width:100%;">
<p align="center"><a href="http://crystal-web.org">Create by Crystal-Web.org</a></p>
</div>
</body>
</html>

 

