
<div class="row" style="margin-top:30px;">
	<!-- Page content -->
	<div class="span16">

	<?php
	$mvc->Plugin->triggerEvents('beforeTitle');
	?>
		<div class="page-header">
			<h1><?php echo $mvc->Page->getPageTitle(); ?></h1>
		</div>
	<?php
	$mvc->Plugin->triggerEvents('afterTitle');
	echo $mvc->Session->flash();
	$mvc->Plugin->triggerEvents('beforeRender');
	echo $mvc->contenu;
	$mvc->Plugin->triggerEvents('onRender');
	?>
	</div>
</div>