<!DOCTYPE html>
<html>
<!--
/************************************************/
/*	  	.:: Par Buffet Christophe ::.	  		*/
/*			.:: 0032(0)/474/171.255 ::.  		*/
/*	.:: Copyright  www.tinyurl.com/copy4u ::.	*/
/*	     .:: http://crystal-web.org ::.         */
/************************************************/
-->
<head>
	<title><?php echo $mvc->Page->getPageTitle() . ' | ' . $mvc->Page->getSiteTitle(); ?></title>
 
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<meta http-equiv="content-language" content="" />
	<meta name="dc.title" content="<?php echo $mvc->Page->getPageTitle() . ' | ' . $mvc->Page->getSiteTitle(); ?>" />
	<meta name="language" content="fr">
	<link rel="icon" type="image/x-icon" href="<?php echo __CW_PATH; ?>/favicon.ico">
	<link rel="icon" type="image/png" href="<?php echo __CW_PATH; ?>/favicon.png">
	
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>

	<link rel="stylesheet" href="http://cdn.crystal-web.org/files/css/bootstrap/1.4.0/bootstrap.min.css">
	<?php echo $mvc->Page->getHeader(); ?>

<link rel=stylesheet type="text/css" href="http://cdn.crystal-web.org/files/css/common.css">
	
<style type="text/css">
body{
background-color: whiteSmoke;
}
</style>

</head>

  <body id="top" <?php echo $mvc->Page->getBody(); ?>>

    <div class="topbar">
      <div class="topbar-inner">
        <div class="container-fluid">
				<h3><a data-placement="below" rel="popover" href="<?php echo __CW_PATH; ?>" id="logo" data-content="Retourner a l'accueil en un clin d'oeil" data-original-title="<?php echo $mvc->Page->getSiteTitle(); ?>"><?php echo $mvc->Page->getSiteTitle(); ?></a></h3>
				<ul>
					<li><a href="<?php echo Router::url('article'); ?>">Article</a></li>
					<li><a href="<?php echo Router::url('calendar'); ?>">Calendrier</a></li>
					<li><a href="<?php echo Router::url('forum'); ?>">Forum</a></li>
				</ul>
				<?php
				if (!$mvc->Session->isLogged())
				{
				?>
				<form action="<?php echo Router::url('auth'); ?>" method="post" class="pull-right">
				<span style="color:#fff;">Connection auto :</span> <input type="checkbox" name="connection_auto">
				<input class="input-small" type="text" name="loginmember" placeholder="Pseudo">
				<input class="input-small" type="password" name="passmember" placeholder="Password">
				<button class="btn" type="submit">Sign in</button>
				</form>
				<?php
				}
				else
				{
				?>
				<ul class="nav secondary-nav">
					<li class="dropdown" data-dropdown="dropdown"><a href="http://www.imagineyourcraft.com/~minecraft/index.php?module=news" class="dropdown-toggle">User Panel</a>
					<ul class="menu-dropdown">
						<li><a href="http://www.imagineyourcraft.com/~minecraft/index.php?module=admin">Tableau de bord</a></li>
						<li><a href="<?php echo Router::url('auth/logout'); ?>">Déconnection</a></li>
					</ul>
					</li>
				</ul>
				<?php
				}
				?>
        </div>
      </div>
    </div>
	
    <div class="container-fluid" style="margin-top:45px;">
 				<?php
				$margin = 'margin-left: 0px !important;';
				$menu = NULL;
				if (count($mvc->Page->getMenu())>0)
				{
				$margin=null;
				$menu = '<div class="sidebar">'.PHP_EOL.'<div class="well">';
	
					$menu .= '
					<audio style="hidden" id="pl">
						<source src="http://beta.crystal-web.org/media/audio/mp3/dyraz.mp3"></source>
						<source src="http://beta.crystal-web.org/media/audio/ogg/dyraz.ogg"></source>
					</audio>
					<div onmouseover="audioElement.play();">
						<a href="http://dyraz.com">
							<img src="http://beta.crystal-web.org/media/image/png/logo.81.png" alt="" />
						</a>
					</div><script type="text/javascript">var audioElement = document.getElementById(\'pl\');
					console.log(audioElement);
					</script>';				
				
					foreach ($mvc->Page->getMenu() AS $name => $listUrl)
					{
					$menu .= '<h5>'.$name.'</h5><ul>';
						foreach ($listUrl AS $data)
						{
						$menu .= '<li><a href="'.$data[0].'">'.$data[1].'</a></li>';
						}
					$menu .= '</ul>';

					}
				$menu .= '	</div>'.PHP_EOL.'</div>';
				}
				
				echo $menu;
				?>
      <div class="content" style="<?php echo $margin; ?>padding: 10px;">
        <div class="row">
          <div class="span16">
            <h2><?php echo $mvc->Page->getPageTitle(); ?></small></h2>
				<?php				
				echo $mvc->Session->flash();
				echo $mvc->contenu;
				?>
          </div>
        </div>
        <hr>
        <footer>
          <p style="font-weight:bold;text-align:center;">Copyright &copy; 2008 - 2012 <?php echo $mvc->Page->getSiteTitle(); ?>. Tous droits r&eacute;s&eacute;rv&eacute;s</p>
        </footer>
      </div>
    </div>

	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/bootstrap-dropdown.js">$('#topbar').dropdown();</script>
	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/bootstrap-tabs.js">$('.tabs').tabs();</script>
	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/bootstrap-alerts.js">$(".alert-message").alert();</script>
	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/tablesorter.js"></script>
	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/bootstrap-twipsy.js"></script>
	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/bootstrap-modal.js"></script>	
	<script type="text/javascript" src="http://cdn.crystal-web.org/files/js/bootstrap/1.4.0/bootstrap-popover.js"></script>
	<script>
	$(function () {
		  $("a[rel=popover]")
			.popover({
			  offset: 10
			})
		})
	</script>
	<script  type="text/javascript" src="http://cdn.crystal-web.org/files/js/common.js"></script>

</body>
</html>
