<?php
class sitemapController extends Controller {
	public function index() {
		$c = new errorController();
		return $c->e403();
	}
	
	private $url = array();
	
	public function xml() {
		$page = Page::getInstance();
		$page->setLayout('empty');
		header("Content-type: text/xml");
		echo '<?xml version="1.0" encoding="UTF-8"?>';
		echo '<urlset ' . PHP_EOL . 
      			'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"' . PHP_EOL . 
				'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' . PHP_EOL . 
				'xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9' . PHP_EOL . 
				'http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">';
		echo '<url>' . PHP_EOL . 
				'<loc>' . Router::url() . '</loc>' . PHP_EOL . 
				'<changefreq>weekly</changefreq>' . PHP_EOL . 
			'</url>';
			
			for($i=0;$i<count($this->url);$i++) {
				echo '<url>' . PHP_EOL . 
					'<loc>' . Router::url($this->url[$i]) . '</loc>' . PHP_EOL . 
					'<changefreq>weekly</changefreq>' . PHP_EOL . 
				'</url>';
			}

		echo '</urlset>';
	}

	public function robots() {
		$page = Page::getInstance();
		$page->setLayout('empty');
		header("Content-type: text/plain");
		?>
# robots.txt generated by http://devphp.me
User-agent: *
Allow: *
Crawl-delay: 120
Disallow: /cgi-bin/
Sitemap: <? echo Router::url('sitemap/xml');
	}
}